---
services:
  eos:
    container_name: eos-victron
    image: maxx3105/eos-victron:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.13.15"
        BUILD_VERSION: "victron-synology"
    env_file:
      - synology.env
    environment:
      OPENBLAS_NUM_THREADS: "1"
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      PIP_PROGRESS_BAR: "off"
      PIP_NO_COLOR: "1"
      EOS_SERVER__HOST: "0.0.0.0"
      EOS_SERVER__PORT: "8503"
      EOS_SERVER__EOSDASH_HOST: "0.0.0.0"
      EOS_SERVER__EOSDASH_PORT: "8504"
    read_only: true
    restart: unless-stopped
    ports:
      - "8503:8503"
      - "8504:8504"
    volumes:
      - ./synology-data:/data:rw
