---
services:
  eos:
    container_name: eos-victron
    image: maxx3105/eos:latest
    restart: unless-stopped
    ports:
      - "8503:8503"
      - "8504:8504"
    volumes:
      - ./synology-data:/data:rw
